# markdown
markdown: redcarpet
redcarpet:
  extensions:
  - smart
  - with_toc_data

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: FITARA Implementation
description: "Resources, best practices, and case studies for CIO management in the federal government."
baseurl: http://open.gsa.gov/CIOmanagement  


# GitHub information
org_name: GSA
repo_name: CIOmanagement
branch: gh-pages


# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /management/
- text: Implementation Guidance
  url: /management/implementation/
- text: Policy Resources
  url: /management/policy/
- text: Agency Dashboard
  url: /management/dashboard/
- text: FAQ
  url: /management/faq/
- text: Join the Community
  url: /management/community/
