# markdown 
markdown: redcarpet
redcarpet:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Management.cio.gov"
description: "Guidance, Resources, and Artifacts to assist agencies in implementing FITARA and other related policies"
baseurl: http://gsa.github.io/CIOmanagement
# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: GSA
repo_name: CIOmanagement
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /CIOmanagement/
- text: Implementation Guidance
  url: /CIOmanagement/implementation/
- text: Policy Resources
  url: /CIOmanagement/policy/
- text: FAQ
  url: /CIOmanagement/faq/
- text: Schemas
  url: /CIOmanagement/schema/
- text: Community Links
  url: /CIOmanagement/community/
- text: Agency Plans
  url: /CIOmanagement/plans/

# sass
sass:
  sass_dir: _sass
